### ISSUE TITLE
Feature request: mypy ignore on rewritten files

### ISSUE THREAD

**Issue by adamtheturtle** [mwilliamson/python-vendorize#1]
Thank you for this project - it has made my life easier.

I have one thing that I am trying to find a workaround for:
* I use `mypy src/my_project`
* I vendor a package which does not have type hints into `src/my_project`
* `mypy` now warns that functions in the vendored code are missing type annotations

`mypy` does not have a CLI option to exclude files, unlike some other linters.
Ideally for me, there would be an option in `python-vendorize` which adds `# type: ignore` to vendored files.

**Comment by adamtheturtle** [comment]
I'm currently using the following workaround:

```
"""
Run `mypy`, ignoring relevant errors.
"""

import subprocess
import sys


def main() -> None:
    args = ['mypy', 'src/', 'tests/']
    ignore_paths = {
        'src/dcos_e2e/_vendor',
    }
    result = subprocess.run(args=args, stdout=subprocess.PIPE)
    result_lines = result.stdout.decode().strip().split('\n')
    error_lines = [
        line for line in result_lines for path in ignore_paths if
        not line.startswith(path)
    ]
    print('\n'.join(error_lines))
    sys.exit(int(bool(error_lines)))


if __name__ == '__main__':
    main()
```

**Comment by mwilliamson** [comment]
Hmm, would running a script that adds a prefix to the files in a directory work for you? So long as you always ran the script immediately after running vendorize, that would seem to solve the problem without a workaround.

**Comment by adamtheturtle** [comment]
@mwilliamson Yes, that would solve the problem but there is no advantage to me really to creating and maintaining that script, over the mypy script I have above. I imagine that bundling something with `python-vendorize` would help others with my use case.

**Comment by adamtheturtle** [comment]
Turns out that `mypy` has an exclude option so this is useless!
