### ISSUE TITLE
unable to vendorise 'netifaces'

### ISSUE THREAD

**Issue by danieleades** [mwilliamson/python-vendorize#15]
i'm attempting to vendorise the 'netifaces' package, but mypy is complaining it can't find the imports

*vendorize.toml*

```toml
target = "src/MY_PACKAGE/_vendor"
packages = [
    "jinja2",
    "netifaces",
]
```

*contents of the `_vendor` package*

```
.
├── Jinja2-3.0.3.dist-info
│   ├── ...
├── __init__.py
├── jinja2
│   ├── ...
├── netifaces-0.11.0.dist-info
│   ├── INSTALLER
│   ├── LICENSE
│   ├── METADATA
│   ├── RECORD
│   ├── REQUESTED
│   ├── WHEEL
│   ├── top_level.txt
│   └── zip-safe
└── netifaces.cpython-39-x86_64-linux-gnu.so
```

was expecting to see a `netifaces` directory.

Is this is an issue with the vendorization, or with mypy?

**Comment by mwilliamson** [comment]
netifaces is a binary package, which vendorize doesn't (and, I suspect, can't) handle.

**Comment by mwilliamson** [comment]
Closing since I don't think there's a way for vendorize to handle binary packages.
