### ISSUE TITLE
Indentation failure of import rewriting

### ISSUE THREAD

**Issue by zwimer** [mwilliamson/python-vendorize#19]
My toml file:
```toml
target = "binsync/vendor"
packages = [
	"GitPython==3.1.20",
]
```

`vendorize` rewrites imports in `git/objects/commit.py`, changing the code from:
```python
465             # as well ...
466             import git.refs
467             try:
```
to:
```python
465             # as well ...
466             from ... import git
467 from ...git import refs as ___vendorize__0
468 git.refs = ___vendorize__0
469             try:
```

As you can see, the two newly inserted lines are not indented.

The `vendorize` version I'm using is: `0.3.0`; the latest on PyPi presently.

If more context about the code snipped is desired, it is this line in on the main branch of the `GitPython` project: https://github.com/gitpython-developers/GitPython/blob/183cf3509f2a1646daaca1874594a27abb408deb/git/objects/commit.py#L554

**Comment by zwimer** [comment]
Is it maybe related to this? https://github.com/mwilliamson/python-vendorize/blob/28c66bbfdc6a46739864a3df8bec60155b0cc50a/vendorize/import_rewrite.py#L55

**Comment by mwilliamson** [comment]
I've had a go at fixing this, could you try testing the latest commit on master?

**Comment by zwimer** [comment]
It works.

**Comment by mwilliamson** [comment]
Great, thanks for trying it out.
