### ISSUE TITLE
PyPi documentation is old/incorrect

### ISSUE THREAD

**Issue by brousch** [mwilliamson/python-vendorize#5]
The example vendorize.toml file in the Github README includes: `packages = [`

However [the documentation on PyPi](https://pypi.org/project/vendorize/) includes: `requires = [`

Using `requires` produces a `KeyError: 'packages'` when python-vendorize is run.

The PyPi documentation should be updated to match the README in Github.

**Comment by mwilliamson** [comment]
I've just released 0.2.1 to PyPI which has the fixed documentation. Apologies for the confusion.
