### ISSUE TITLE
Rewrite imports

### ISSUE THREAD

**Issue by thedrow** [mwilliamson/python-vendorize#7]
Currently this tool only downloads the packages.
It should automatically rewrite the imports as well.

**Comment by thedrow** [comment]
Oh I see that there is code that does so.
I'm not sure why it didn't for me.

**Comment by thedrow** [comment]
`_read_top_level_names` seems wrong.
I'm not sure how exactly yet.

**Comment by thedrow** [comment]
You shouldn't collect the top level names one at the time.

**Comment by mwilliamson** [comment]
Thanks for the report, this should be addressed in master now.
